site_name: Unofficial APC UPS protocol
site_description: Unofficial APC UPS protocol
site_url: https://kirbah.github.io/apc-ups/
repo_name: 'kirbah/apc-ups'
repo_url: 'https://github.com/kirbah/apc-ups'
edit_uri: 'https://github.com/kirbah/apc-ups/blob/master/docs/'

strict: true

theme: 
  name: material
  palette:
    primary: 'blue'
    accent: 'indigo'
  locale: en
  features:
    - navigation.tabs
  font:
    text: Barlow
    code: Roboto Mono

markdown_extensions:
  - admonition
  - toc:
     permalink: "~"
     toc_depth: 3
  - pymdownx.mark
  - pymdownx.emoji:
  - pymdownx.betterem
  - pymdownx.caret
  - codehilite
  - meta

plugins:
  - search
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: G-TRJ1V77BBM
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

nav: 
  - Home: README.md
  - Smart UPS protocol: Smart-protocol.md
  - UPS Constants: UPS-constants.md
  - Setup examples:
    - SUA1500i: Setup-example-SUA1500i.md
  - Contributing: Contributing.md
