site_name: Unofficial APC UPS protocol
site_description: Unofficial APC UPS protocol
site_url: https://kirbah.github.io/apc-ups/
repo_name: 'kirbah/apc-ups'
repo_url: 'https://github.com/kirbah/apc-ups'
edit_uri: 'https://github.com/kirbah/apc-ups/blob/master/docs/'

strict: true

theme: 
  name: mkdocs
  locale: en
    analytics: {gtag: 'G-TRJ1V77BBM'}
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - toc:
     permalink: "~"
     toc_depth: 3
  - pymdownx.mark
  - pymdownx.emoji:
  - pymdownx.betterem
  - pymdownx.caret
  - codehilite
  - meta

plugins:
  - search

nav: 
  - Home: README.md
  - Smart UPS protocol: Smart-protocol.md
  - UPS Constants: UPS-constants.md
  - Setup examples:
    - SUA1500i: Setup-example-SUA1500i.md
  - Contributing: Contributing.md
